[COVID-3909
color/lokalise-actions pull request #14
Opened 2021-06-30 01:08 UTC by chrisdchow

2021-06-30 16:13 UTC, abatilo requested changes
Seems mostly fine overall as a first pass. We should clean up documentation and usage as a fast follow.

Some small requests though.

2021-06-30 16:13 UTC, abatilo commented on CODEOWNERS
>  * @actions/actions-runtime
```suggestion
```

We don't want/need another org to be the CODEOWNER

2021-06-30 16:13 UTC, abatilo commented on CODEOWNERS
> +/src @color/tide
```suggestion
* @color/tide @chrisdchow
```

Let's just default this to have you and TIDE own all of it for now.

2021-06-30 16:13 UTC, abatilo commented on src/lokalise/types.ts
> +export enum COLOR_LANGUAGE_ISO_CODE {
Can we remove the `COLOR` prefix here? This is an open source project so we should not couple our code directly if we can help it.

2021-06-30 17:39 UTC, chrisdchow commented
@abatilo thanks for the review! I meant to open this as a draft. I'll address your changes, tidy up the documentation, and finish my PR description 🙈 .

2021-07-01 18:32 UTC, abatilo requested changes
One quick change for the README. Otherwise LGTM.

2021-07-01 18:32 UTC, abatilo commented on README.md
>  ```
```suggestion
```yaml
```

2021-07-01 18:36 UTC, merged