Make Color front-end guild owners of repo
color/lokalise-actions pull request #223
Opened 2023-04-04 20:07 UTC by rymarren

2023-04-10 19:45 UTC, abatilo requested changes
If we want to make the frontend guild own this, shouldn't we make the owners the frontend guild vs you as an individual?

2023-04-10 19:51 UTC, rymarren commented
> If we want to make the frontend guild own this, shouldn't we make the owners the frontend guild vs you as an individual?

Oh ya, I was testing to see if it worked for me, since when I add @color/frontend-guild I got this error
```
Unknown owner on line 1: make sure the team @color/frontend-guild exists, is publicly visible, and has write access to the repository
* @color/frontend-guild
```
Is it possible to add @color/frontend-guild to have write access?

2023-04-11 12:57 UTC, jfalkner-color approved these changes

2023-04-11 14:30 UTC, abatilo approved these changes

2023-04-11 15:12 UTC, merged